// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebAppStudent.Base
{
   public partial class People
   {
      public int Id { get; set; }

      [Required(ErrorMessage = "Digite o nome completo")]
      public string Name { get; set; }
      public bool Active { get; set; }
   }
}